name: CI
on:
  push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: gcc -o teak teak.c -pthread -ldl && ./teak build.teak runTests=true && ./teak build.teak runTests=true debug=y && ./teak build.teak runTests=true debug=y stressHeap=true
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: linux_tests_log.txt
        path: tests_log.txt
  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: gcc -o teak teak.c -pthread -ldl && ./teak build.teak runTests=true
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: macos_tests_log.txt
        path: tests_log.txt
  build-win32:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        cl.exe teak.c
        teak.exe build.teak runTests=true
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: win32_tests_log.txt
        path: tests_log.txt
